client_id = "e8b514a99ecab7a30a8bb65b97e9c144"
name = "ActualPrice Public"
application_url = "https://social-sentiment-pricing-staging-2ecd.up.railway.app/api/v1/integrations/shopify/install"
embedded = true

[webhooks]
api_version = "2025-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://social-sentiment-pricing-staging-2ecd.up.railway.app/api/v1/integrations/shopify/gdpr/customers/redact"
  customer_data_request_url = "https://social-sentiment-pricing-staging-2ecd.up.railway.app/api/v1/integrations/shopify/gdpr/customers/data_request"
  shop_deletion_url = "https://social-sentiment-pricing-staging-2ecd.up.railway.app/api/v1/integrations/shopify/gdpr/shop/redact"

[access_scopes]
scopes = "read_inventory,read_orders,read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://social-sentiment-pricing-staging-2ecd.up.railway.app/api/v1/integrations/oauth/callback",
  "https://social-sentiment-pricing.vercel.app/api/v1/integrations/oauth/callback",
  "https://ssp-staging.vercel.app/api/v1/integrations/oauth/callback"
]

