// Pricing Module Types
// AUTO-SYNCED with backend via openapi-typescript
// Last synced: 2026-01-08
// Source: components["schemas"]["PricingRuleCreate"], PricingRuleResponse, etc.

import type { PaginatedResponse } from './common';

// AP-022: OutcomeLabel was defined here AND in outcome.ts — duplicate type definition.
// Removed the local definition and imported from outcome.ts as the single source of truth.
// outcome.ts is the correct home since OutcomeLabel belongs to the Intelligence Environment.
export type { OutcomeLabel } from './outcome';

// ============================================
// ENUMS / UNION TYPES
// Matches: components["schemas"]["RuleType"], RuleAction, RecommendationStatus
// ============================================

/** Types of pricing rules that can trigger recommendations */
export type RuleType =
  | 'sentiment_threshold'
  | 'competitor_relative'
  | 'time_based'
  | 'volume_surge'
  | 'viral_detection';

/** Actions a pricing rule can take when triggered */
export type RuleAction =
  | 'increase_percent'
  | 'decrease_percent'
  | 'set_absolute'
  | 'match_competitor'
  | 'undercut_competitor';

/** Status of a price recommendation through its lifecycle */
export type RecommendationStatus =
  | 'pending'
  | 'auto_approved'
  | 'approved'
  | 'rejected'
  | 'applied'
  | 'expired';

// ============================================
// PRICING RULE TYPES
// ============================================

/**
 * A pricing rule response from GET endpoints
 * Matches: components["schemas"]["PricingRuleResponse"]
 */
export interface PricingRule {
  id: string;
  user_id: string;
  product_id: string | null;
  name: string;
  description: string | null;
  rule_type: RuleType;
  is_active: boolean;
  priority: number;

  // Scope
  applies_to_all_products: boolean;
  applies_to_products: string[] | null;
  applies_to_categories: string[] | null;

  // Conditions - all Decimals returned as strings
  sentiment_threshold: string | null;
  sentiment_direction: string | null;
  competitor_id: string | null;
  competitor_margin_percent: string | null;
  price_position: string | null;
  time_days: string | null;
  time_start: string | null;
  time_end: string | null;
  volume_threshold: number | null;
  volume_window_hours: number | null;
  viral_threshold_reach: number | null;
  viral_threshold_engagement: number | null;
  viral_sentiment_min: string | null;

  // Action - Decimals as strings in response
  action: RuleAction;
  action_value: string;

  // Constraints - Decimals as strings in response
  max_change_percent: string | null;
  min_price: string | null;
  max_price: string | null;
  cooldown_hours: number;

  created_at: string;
  updated_at: string;
}

/**
 * Data required to create a new pricing rule
 * Matches: components["schemas"]["PricingRuleCreate"]
 *
 * Note: Decimal fields accept number | string for flexibility
 * Backend Pydantic will coerce to Decimal
 */
export interface CreatePricingRuleRequest {
  // Scope
  product_id?: string | null;
  applies_to_all_products?: boolean;
  applies_to_products?: string[] | null;
  applies_to_categories?: string[] | null;

  // Basic info
  name: string;
  description?: string | null;
  rule_type: RuleType;
  is_active?: boolean;
  priority?: number;

  // Conditions - accept number | string for Decimals
  sentiment_threshold?: number | string | null;
  sentiment_direction?: string | null;
  competitor_id?: string | null;
  competitor_margin_percent?: number | string | null;
  price_position?: string | null;
  time_days?: string | null;
  time_start?: string | null;
  time_end?: string | null;
  volume_threshold?: number | null;
  volume_window_hours?: number | null;
  viral_threshold_reach?: number | null;
  viral_threshold_engagement?: number | null;
  viral_sentiment_min?: number | string | null;

  // Action - REQUIRED, accepts number | string
  action: RuleAction;
  action_value: number | string;

  // Constraints - accept number | string for Decimals
  min_price?: number | string | null;
  max_price?: number | string | null;
  max_change_percent?: number | string;
  cooldown_hours?: number;
}

/** Data for updating an existing pricing rule */
export type UpdatePricingRuleRequest = Partial<CreatePricingRuleRequest>;

// ============================================
// PRICE RECOMMENDATION TYPES
// ============================================

/**
 * A price recommendation generated by the pricing engine
 * Matches: components["schemas"]["RecommendationResponse"]
 */
export interface PriceRecommendation {
  id: string;
  user_id: string;
  product_id: string;
  rule_id: string | null;
  current_price: string;
  recommended_price: string;
  change_percent: number;
  confidence_score: number;
  reasoning: string;
  factors: Record<string, unknown>;
  status: RecommendationStatus;
  requires_approval: boolean;
  reviewed_by: string | null;
  reviewed_at: string | null;
  rejection_reason: string | null;
  applied_at: string | null;
  applied_to_platform: string | null;
  expires_at: string;
  created_at: string;
}

/** Paginated list of recommendations */
export type PaginatedRecommendations = PaginatedResponse<PriceRecommendation>;

/** Paginated list of pricing rules */
export type PaginatedPricingRules = PaginatedResponse<PricingRule>;

/** Data for approving a recommendation */
export interface ApproveRecommendationRequest {
  notes?: string;
}

/** Data for rejecting a recommendation */
export interface RejectRecommendationRequest {
  reason?: string | null;
}

// ============================================
// PRICING SETTINGS TYPES
// Matches: components["schemas"]["PricingSettingsResponse"]
// ============================================

/** User's pricing settings/preferences */
export interface PricingSettings {
  id: string;
  user_id: string;
  auto_approve_enabled: boolean;
  auto_approve_max_increase: number;
  auto_approve_max_decrease: number;
  auto_approve_min_confidence: number;
  min_margin_percent: number;
  max_auto_changes_per_day: number;
  global_cooldown_hours: number;
  blackout_hours_start: number | null;
  blackout_hours_end: number | null;
  require_approval_above_price: number | null;
  recommendation_valid_hours: number;
  notify_on_auto_apply: boolean;
  notify_on_pending: boolean;
  notification_email: string | null;
  notification_slack_webhook: string | null;
  created_at: string;
  updated_at: string | null;
}

/**
 * Data for updating pricing settings
 * Matches: components["schemas"]["PricingSettingsUpdate"]
 */
export interface UpdatePricingSettingsRequest {
  auto_approve_enabled?: boolean;
  auto_approve_max_increase?: number;
  auto_approve_max_decrease?: number;
  auto_approve_min_confidence?: number;
  min_margin_percent?: number;
  max_auto_changes_per_day?: number;
  global_cooldown_hours?: number;
  blackout_hours_start?: number | null;
  blackout_hours_end?: number | null;
  require_approval_above_price?: number | null;
  recommendation_valid_hours?: number;
  notify_on_auto_apply?: boolean;
  notify_on_pending?: boolean;
  notification_email?: string | null;
  notification_slack_webhook?: string | null;
}

/**
 * Statistics about pricing recommendations
 * Matches: components["schemas"]["RecommendationStats"]
 */
export interface PricingRecommendationStats {
  total_generated: number;
  total_applied: number;
  total_rejected: number;
  total_expired: number;
  total_pending: number;
  approval_rate: number;
  avg_confidence: number | null;
  avg_price_change_percent: number | null;
}

/**
 * Structured error response from pricing approval endpoints
 */
export interface ApprovalErrorDetail {
  message: string;
  error_code: string;
  suggestion: string;
}

/**
 * Error codes returned by approval endpoints
 */
export type ApprovalErrorCode =
  | 'DAILY_LIMIT_REACHED'
  | 'NO_ACTIVE_INTEGRATION_LINK'
  | 'PRODUCT_NOT_LINKED'
  | 'PLATFORM_PUSH_FAILED'
  | 'RECOMMENDATION_EXPIRED'
  | 'INVALID_STATUS'
  | 'NOT_FOUND'
  | 'PRODUCT_NOT_FOUND'
  | 'APPROVAL_ERROR';


  