// Pricing Module Types
// Types for pricing rules, recommendations, and settings
// Aligned with backend/schemas/pricing.py

import type { PaginatedResponse, AlertChannel } from './common';

// ============================================
// ENUMS / UNION TYPES
// ============================================

/** Types of pricing rules that can trigger recommendations */
export type RuleType =
  | 'sentiment_threshold'
  | 'competitor_relative'
  | 'time_based'
  | 'volume_surge'
  | 'viral_detection';

/** Actions a pricing rule can take when triggered */
export type RuleAction =
  | 'increase_percent'
  | 'decrease_percent'
  | 'set_absolute'
  | 'match_competitor'
  | 'undercut_competitor';

/** Status of a price recommendation through its lifecycle */
export type RecommendationStatus =
  | 'pending'
  | 'auto_approved'
  | 'approved'
  | 'rejected'
  | 'applied'
  | 'expired';

/** Outcome label for measuring recommendation effectiveness */
export type OutcomeLabel = 'positive' | 'negative' | 'neutral' | 'inconclusive';

// ============================================
// PRICING RULE TYPES
// ============================================

/** A pricing rule that defines conditions and actions for automatic pricing */
export interface PricingRule {
  id: string;
  user_id: string;
  product_id: string;
  name: string;
  description: string | null;
  rule_type: RuleType;
  is_active: boolean;
  priority: number;

  // Conditions
  sentiment_threshold: number | null;
  sentiment_direction: string | null;
  competitor_id: string | null;
  price_position: string | null;
  time_days: number | null;
  volume_threshold: number | null;
  viral_threshold_reach: number | null;

  // Action
  action: RuleAction;
  action_value: string;

  // Constraints
  max_change_percent: string | null;
  min_price: string | null;
  max_price: string | null;
  cooldown_hours: number;

  // Scope
  applies_to_products: string[] | null;
  applies_to_categories: string[] | null;

  created_at: string;
  updated_at: string;
}

/** Data required to create a new pricing rule */
export interface CreatePricingRuleRequest {
  product_id: string;
  name: string;
  description?: string;
  rule_type: RuleType;
  is_active?: boolean;
  priority?: number;
  sentiment_threshold?: number;
  sentiment_direction?: string;
  competitor_id?: string;
  price_position?: string;
  time_days?: number;
  volume_threshold?: number;
  viral_threshold_reach?: number;
  action: RuleAction;
  action_value: string;
  max_change_percent?: string;
  min_price?: string;
  max_price?: string;
  cooldown_hours?: number;
  applies_to_products?: string[];
  applies_to_categories?: string[];
}

/** Data for updating an existing pricing rule */
export type UpdatePricingRuleRequest = Partial<CreatePricingRuleRequest>;

// ============================================
// PRICE RECOMMENDATION TYPES
// ============================================

/** A price recommendation generated by the pricing engine */
export interface PriceRecommendation {
  id: string;
  user_id: string;
  product_id: string;
  rule_id: string | null;
  current_price: string;
  recommended_price: string;
  change_percent: number;
  confidence_score: number;
  reasoning: string;
  factors: Record<string, unknown>;
  status: RecommendationStatus;
  requires_approval: boolean;
  reviewed_by: string | null;
  reviewed_at: string | null;
  rejection_reason: string | null;
  applied_at: string | null;
  expires_at: string;
  created_at: string;
}

/** Paginated list of recommendations */
export type PaginatedRecommendations = PaginatedResponse<PriceRecommendation>;

/** Paginated list of pricing rules */
export type PaginatedPricingRules = PaginatedResponse<PricingRule>;

/** Data for approving a recommendation */
export interface ApproveRecommendationRequest {
  notes?: string;
}

/** Data for rejecting a recommendation */
export interface RejectRecommendationRequest {
  reason: string;
}

// ============================================
// PRICING SETTINGS TYPES
// ============================================

/** User's pricing settings/preferences */
export interface PricingSettings {
  id: string;
  user_id: string;
  auto_apply_enabled: boolean;
  auto_apply_max_percent: string;
  require_approval_above: string;
  min_confidence_threshold: number;
  default_cooldown_hours: number;
  notification_channels: AlertChannel[];
  created_at: string;
  updated_at: string;
}

/** Data for updating pricing settings */
export interface UpdatePricingSettingsRequest {
  auto_apply_enabled?: boolean;
  auto_apply_max_percent?: string;
  require_approval_above?: string;
  min_confidence_threshold?: number;
  default_cooldown_hours?: number;
  notification_channels?: AlertChannel[];
}

/** Statistics about pricing recommendations (from pricing API) */
export interface PricingRecommendationStats {
  total_generated: number;
  total_applied: number;
  total_rejected: number;
  total_expired: number;
  total_pending: number;
  approval_rate: number;
  avg_confidence: number | null;
  avg_price_change_percent: number | null;
}
