"""add full_name and product fields

Revision ID: 0f65b2d9de7c
Revises: ae4a25042fb1
Create Date: 2025-12-07 22:01:27.234431

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f65b2d9de7c"
down_revision: str | Sequence[str] | None = "ae4a25042fb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("price_history", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "price_history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_price_history_user_id"), "price_history", ["user_id"], unique=False)
    op.drop_constraint(op.f("price_history_product_id_fkey"), "price_history", type_="foreignkey")
    op.drop_column("price_history", "triggered_by")
    op.drop_column("price_history", "sentiment_score_at_change")
    op.drop_column("price_history", "sentiment_volume")
    op.add_column("products", sa.Column("category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column("products", sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("products", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")))
    op.add_column("users", sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    op.drop_column("products", "is_active")
    op.drop_column("products", "image_url")
    op.drop_column("products", "category")
    op.add_column("price_history", sa.Column("sentiment_volume", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "price_history",
        sa.Column("sentiment_score_at_change", sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    )
    op.add_column("price_history", sa.Column("triggered_by", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("price_history_product_id_fkey"), "price_history", "products", ["product_id"], ["id"])
    op.drop_index(op.f("ix_price_history_user_id"), table_name="price_history")
    op.alter_column(
        "price_history",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column("price_history", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
