"""add_social_mentions_table

Revision ID: a69d3882761a
Revises: phase2_competitors
Create Date: 2025-11-30 09:58:32.460395

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a69d3882761a"
down_revision: str | Sequence[str] | None = "phase2_competitors"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("author_followers", sa.Integer(), nullable=True),
        sa.Column("engagement_count", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_social_mentions_processed"), "social_mentions", ["processed"], unique=False)
    op.create_index(op.f("ix_social_mentions_product_id"), "social_mentions", ["product_id"], unique=False)
    op.create_index(op.f("ix_social_mentions_source"), "social_mentions", ["source"], unique=False)
    op.create_index(op.f("ix_social_mentions_source_id"), "social_mentions", ["source_id"], unique=False)
    op.create_index(op.f("ix_social_mentions_user_id"), "social_mentions", ["user_id"], unique=False)
    op.drop_table("playing_with_neon")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "playing_with_neon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.REAL(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("playing_with_neon_pkey")),
    )
    op.drop_index(op.f("ix_social_mentions_user_id"), table_name="social_mentions")
    op.drop_index(op.f("ix_social_mentions_source_id"), table_name="social_mentions")
    op.drop_index(op.f("ix_social_mentions_source"), table_name="social_mentions")
    op.drop_index(op.f("ix_social_mentions_product_id"), table_name="social_mentions")
    op.drop_index(op.f("ix_social_mentions_processed"), table_name="social_mentions")
    op.drop_table("social_mentions")
    # ### end Alembic commands ###
