"""add FK constraints to pricing models

Revision ID: eb1b1cb111ad
Revises: price_check_001
Create Date: 2026-03-21 22:05:44.164189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb1b1cb111ad'
down_revision: Union[str, Sequence[str], None] = 'price_check_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_assignments_category_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_merchant_id'), table_name='experiment_assignments')
    op.drop_index(op.f('ix_experiment_assignments_recommendation_id'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_prospect_audit_events_created_at'), table_name='prospect_audit_events')
    op.drop_index(op.f('ix_prospect_audit_events_event_type'), table_name='prospect_audit_events')
    op.drop_table('prospect_audit_events')
    op.drop_index(op.f('ix_audit_requests_converted'), table_name='audit_requests')
    op.drop_index(op.f('ix_audit_requests_created_at'), table_name='audit_requests')
    op.drop_index(op.f('ix_audit_requests_email'), table_name='audit_requests')
    op.drop_index(op.f('ix_audit_requests_store_url'), table_name='audit_requests')
    op.drop_table('audit_requests')
    op.drop_table('competitor_prices')
    op.drop_index(op.f('uq_bandit_state_category_id'), table_name='bandit_state')
    op.drop_table('bandit_state')
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('alerts', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('alerts', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('alerts', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('integration_sync_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('integration_sync_logs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('integrations', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('integrations', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'amount_raw',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.create_foreign_key(None, 'price_recommendations', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'price_recommendations', 'pricing_rules', ['triggered_rule_id'], ['id'])
    op.create_foreign_key(None, 'price_recommendations', 'users', ['user_id'], ['id'])
    op.drop_column('price_recommendations', 'scoring_version')
    op.alter_column('pricing_rules', 'price_position',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'pricing_rules', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'pricing_rules', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'pricing_settings', 'users', ['user_id'], ['id'])
    op.alter_column('product_integration_links', 'last_price_pull_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('uq_link_integration_product_variant'), table_name='product_integration_links')
    op.create_unique_constraint('uq_link_integration_product_variant', 'product_integration_links', ['integration_id', 'external_product_id', 'external_variant_id'])
    op.create_index(op.f('ix_product_integration_links_external_variant_id'), 'product_integration_links', ['external_variant_id'], unique=False)
    op.drop_index(op.f('ix_outcomes_category_created'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_outcomes_confidence_lift'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_outcomes_measurement_status'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_outcomes_merchant_decision'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_bandit_unprocessed'), table_name='recommendation_outcomes', postgresql_where='(bandit_processed = false)')
    op.drop_index(op.f('ix_recommendation_outcomes_strategy_arm'), table_name='recommendation_outcomes', postgresql_where='(strategy_arm IS NOT NULL)')
    op.create_foreign_key(None, 'recommendation_outcomes', 'pricing_rules', ['rule_id'], ['id'])
    op.create_foreign_key(None, 'recommendation_outcomes', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'recommendation_outcomes', 'price_recommendations', ['recommendation_id'], ['id'])
    op.create_foreign_key(None, 'recommendation_outcomes', 'users', ['user_id'], ['id'])
    op.drop_column('recommendation_outcomes', 'is_exploration')
    op.drop_column('recommendation_outcomes', 'bandit_processed')
    op.drop_column('recommendation_outcomes', 'scoring_version')
    op.drop_column('recommendation_outcomes', 'experiment_assignment_id')
    op.drop_column('recommendation_outcomes', 'strategy_arm')
    op.alter_column('retrospective_audits', 'summary_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('retrospective_audits', 'sku_results_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_index(op.f('ix_retrospective_audits_user_created'), table_name='retrospective_audits')
    op.drop_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_retrospective_audits_user_created'), 'retrospective_audits', ['user_id', 'created_at'], unique=False)
    op.alter_column('retrospective_audits', 'sku_results_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('retrospective_audits', 'summary_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('recommendation_outcomes', sa.Column('strategy_arm', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recommendation_outcomes', sa.Column('experiment_assignment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('recommendation_outcomes', sa.Column('scoring_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_outcomes', sa.Column('bandit_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('recommendation_outcomes', sa.Column('is_exploration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recommendation_outcomes', type_='foreignkey')
    op.drop_constraint(None, 'recommendation_outcomes', type_='foreignkey')
    op.drop_constraint(None, 'recommendation_outcomes', type_='foreignkey')
    op.drop_constraint(None, 'recommendation_outcomes', type_='foreignkey')
    op.create_index(op.f('ix_recommendation_outcomes_strategy_arm'), 'recommendation_outcomes', ['strategy_arm'], unique=False, postgresql_where='(strategy_arm IS NOT NULL)')
    op.create_index(op.f('ix_recommendation_outcomes_bandit_unprocessed'), 'recommendation_outcomes', ['bandit_processed'], unique=False, postgresql_where='(bandit_processed = false)')
    op.create_index(op.f('ix_outcomes_merchant_decision'), 'recommendation_outcomes', ['user_id', 'merchant_decision'], unique=False)
    op.create_index(op.f('ix_outcomes_measurement_status'), 'recommendation_outcomes', ['measurement_status', 'price_applied_at'], unique=False)
    op.create_index(op.f('ix_outcomes_confidence_lift'), 'recommendation_outcomes', ['original_confidence', 'revenue_lift_7d'], unique=False)
    op.create_index(op.f('ix_outcomes_category_created'), 'recommendation_outcomes', ['product_category', 'created_at'], unique=False)
    op.drop_index(op.f('ix_product_integration_links_external_variant_id'), table_name='product_integration_links')
    op.drop_constraint('uq_link_integration_product_variant', 'product_integration_links', type_='unique')
    op.create_index(op.f('uq_link_integration_product_variant'), 'product_integration_links', ['integration_id', 'external_product_id', 'external_variant_id'], unique=True)
    op.alter_column('product_integration_links', 'last_price_pull_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'pricing_settings', type_='foreignkey')
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.alter_column('pricing_rules', 'price_position',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('price_recommendations', sa.Column('scoring_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'price_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'price_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'price_recommendations', type_='foreignkey')
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.alter_column('payments', 'amount_raw',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('integrations', 'last_sync_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('integrations', 'token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('integration_sync_logs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('integration_sync_logs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('alerts', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alerts', 'acknowledged_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alerts', 'sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('bandit_state',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('arm_states', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('total_pulls', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('converged_arm', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('convergence_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bandit_state_pkey'))
    )
    op.create_index(op.f('uq_bandit_state_category_id'), 'bandit_state', ['category_id'], unique=True)
    op.create_table('competitor_prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('competitor_product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('new_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('change_percent', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('detected_promotion', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('promotion_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('was_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scraped_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('scrape_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('observed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('audit_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('store_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('products_scanned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competitors_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_monthly_impact', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_annual_impact', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('converted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ip_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_requests_pkey'))
    )
    op.create_index(op.f('ix_audit_requests_store_url'), 'audit_requests', ['store_url'], unique=False)
    op.create_index(op.f('ix_audit_requests_email'), 'audit_requests', ['email'], unique=False)
    op.create_index(op.f('ix_audit_requests_created_at'), 'audit_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_requests_converted'), 'audit_requests', ['converted'], unique=False)
    op.create_table('prospect_audit_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('store_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('input_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('products_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_impact', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prospect_audit_events_pkey'))
    )
    op.create_index(op.f('ix_prospect_audit_events_event_type'), 'prospect_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_prospect_audit_events_created_at'), 'prospect_audit_events', ['created_at'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('recommendation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('strategy_arm', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('arm_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_exploration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('strategy_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_assignments_pkey'))
    )
    op.create_index(op.f('ix_experiment_assignments_recommendation_id'), 'experiment_assignments', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_merchant_id'), 'experiment_assignments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_experiment_assignments_category_id'), 'experiment_assignments', ['category_id'], unique=False)
    # ### end Alembic commands ###
