"""add_integration_tables

Revision ID: fe5f2a6d2e42
Revises: a69d3882761a
Create Date: 2025-12-01 06:47:12.076952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fe5f2a6d2e42'
down_revision: Union[str, Sequence[str], None] = 'a69d3882761a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('SHOPIFY', 'WOOCOMMERCE', name='ecommerceplatform'), nullable=False),
    sa.Column('store_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'PAUSED', 'DISCONNECTED', name='integrationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('webhook_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('oauth_state', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('products_synced', sa.Integer(), nullable=False),
    sa.Column('sync_cursor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_platform'), 'integrations', ['platform'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('integration_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('products_created', sa.Integer(), nullable=False),
    sa.Column('products_updated', sa.Integer(), nullable=False),
    sa.Column('products_deleted', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_logs_integration_id'), 'integration_sync_logs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_sync_logs_started_at'), 'integration_sync_logs', ['started_at'], unique=False)
    op.create_table('product_integration_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('external_product_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('external_variant_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('external_price', sa.Float(), nullable=True),
    sa.Column('external_compare_at_price', sa.Float(), nullable=True),
    sa.Column('last_price_push_at', sa.DateTime(), nullable=True),
    sa.Column('last_price_pull_at', sa.DateTime(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_integration_links_external_product_id'), 'product_integration_links', ['external_product_id'], unique=False)
    op.create_index(op.f('ix_product_integration_links_integration_id'), 'product_integration_links', ['integration_id'], unique=False)
    op.create_index(op.f('ix_product_integration_links_product_id'), 'product_integration_links', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_integration_links_product_id'), table_name='product_integration_links')
    op.drop_index(op.f('ix_product_integration_links_integration_id'), table_name='product_integration_links')
    op.drop_index(op.f('ix_product_integration_links_external_product_id'), table_name='product_integration_links')
    op.drop_table('product_integration_links')
    op.drop_index(op.f('ix_integration_sync_logs_started_at'), table_name='integration_sync_logs')
    op.drop_index(op.f('ix_integration_sync_logs_integration_id'), table_name='integration_sync_logs')
    op.drop_table('integration_sync_logs')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_platform'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
